version: 2
jobs:
  build:
    # set Docker image
    docker:
      - image: circleci/node:8.9.4-browsers
    working_directory: ~/app

    # build steps
    steps:
      - checkout

      # install requirement
      - run:
          name: Install requirement by npm
          command: npm install

      # build from webpack
      - run:
          name: Build from webpack
          command: npm run build

      # run eslint(static code analyze)
      - run:
          name: Run eslint(static code analyze)
          command: npm run eslint

